### ISSUE TITLE
Stash items cannot be picked up with Tiles Course Format

### ISSUE THREAD

**Issue by sanjan1809** [abgreeve/moodle-block_stash#13]
Issue from cborn in annother repository: We have a course using the Tiles Course Format, and the Stash items are not reacting to button clicks when a section is open in the overlay mode. Is there a workaround for this?

I´m using Tiles Course format too and have the same "problem". Would be happy about a solution :)

**Comment by cborn** [comment]
Thanks for posting here, @sanjan1809 !  I'm anxious to learn about a fix or workaround!

**Comment by abgreeve** [comment]
Sorry, nothing that I can do here. I had a look at the course tiles format, and the reason that it doesn't work is because the page activity has been moved into a modal and the author of the tiles format hasn't retrieved the JavaScript to allow the stash item to be picked up. Please file a problem with their tracker to resolve this issue.

**Comment by abgreeve** [comment]
An update here. There is a pull request on the tiles course format tacker site, which will solve this issue. It unfortunately has not been integrated yet. Please contact David Watson and ask him to pull in pull request 24.
